# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('icon_image', models.ImageField(upload_to='media/')),
                ('css_id', models.CharField(max_length=20)),
                ('url', models.URLField()),
            ],
        ),
    ]
